print("karan \nsimran \ngeeta \npradeep \nmummy")
print("\n")
print("karan ","simran" ,"geeta ", "pradeep ", "mummy",sep="\n")
print("\n")
print("karan")
print("simran")
print("geeta")
print("pradeep")
print("mummy")
